server:
  port: 8080


logging:
  level:
    com.tech.gateway.filter: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: WARN
spring:
  application:
    name: gateway-service



  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://booking-service:8081
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1

        - id: show-service
          uri: http://show-service:8082
          predicates:
            - Path=/show/**
          filters:
            - StripPrefix=1

        - id: movie-service
          uri: http://movie-service:8083
          predicates:
            - Path=/movie/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: theatre-service
          uri: http://theatre-service:8085
          predicates:
            - Path=/theatre/**
          filters:
            - StripPrefix=1

        - id: discount-service
          uri: http://discount-service:8086
          predicates:
            - Path=/discount/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: http://payment-service:8087
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://auth-service:8088
          predicates:
            - Path=/auth/**
          filters:
          - StripPrefix=1
  security:
    user:
          name: disabled
          password: disabled
          basic:
            enabled: false
